/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'duke' at '14/06/29 21:17' with Gradle 1.12
 *
 * @author duke, @date 14/06/29 21:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
